# Dynamic configuration

tls:
  stores:
    default: { }
  certificates:
    - certFile: /run/secrets/secret.crt
      keyFile: /run/secrets/secret.key
      stores:
        - default

http:
  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true