# Static configuration

accessLog: {}

###> For the production it's better to specify external metrics gathering tool like Prometheus/Influx or something
#metrics:
#  influxDB:
#    address: somehost:8089

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    swarmMode: true
    network: "internal"
  file:
    filename: "/etc/traefik/dynamic.yaml"